import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GameX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-50 drop-shadow-[0px_16px_32px_rgba(0,0,0,0.35)]">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
